Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2023-09, with the labels that each got.

#159 [optimize] Jump to Gaode Map
  components/ListMap.tsx
Labels: enhancement

#161 [fix] Geo Location bug of GaoDe Web service
  components/ListMap.tsx
  package.json
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
Labels: bug

#164 [optimize] delete too many article list
  components/Layout/MDX.tsx
  pages/article/[id]/index.tsx
Labels: bug

#158 Feat issues page
  components/Issues/IssueModule.module.less
  components/Issues/IssueModule.tsx
  components/data.ts
  models/Base/index.ts
  models/Repository.ts
  package.json
  pages/member/index.tsx
  pages/project/issues/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#166 [add] Issue Card component
  components/Activity/Card.tsx
  components/Article/Card.tsx
  components/Issues/Card.tsx
  components/Issues/IssueModule.module.less
  components/Issues/IssueModule.tsx
  components/data.ts
  models/Activity/Forum.ts
  package.json
  pages/_document.tsx
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/project/issues/index.tsx
  pnpm-lock.yaml
  styles/globals.less
Labels: enhancement

#154 feat: volunteer page
  models/Activity/Staff.ts
  models/Activity/index.ts
  pages/activity/[id]/volunteer.tsx
Labels: feature

#168 [fix] several UI bugs of Activity Volunteer & GitHub Issue pages
  components/Issues/IssueModule.tsx
  components/Member/Card.module.less
  models/Activity/Place.ts
  models/Activity/Staff.ts
  pages/activity/[id]/index.tsx
  pages/activity/[id]/volunteer.tsx
  pages/project/issues/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#165 feature :add KCC member's photo wall
  .env
  components/Community/CommunityCard.tsx
  components/Community/List.tsx
  components/Community/MemberCard.tsx
  components/Community/MemberList.tsx
  components/data.ts
  models/Community/CommunityMember.ts
  models/Community/index.ts
  pages/api/search.ts
  pages/community/[community].tsx
  pages/community/index.tsx
  pages/member/[name].tsx
  pages/search/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#173 [add] Authorization checking of Activity Agenda
  components/Activity/Agenda/Toolbar.tsx
  components/Community/CommunityCard.tsx
  components/Community/List.tsx
  components/Issues/IssueModule.tsx
  components/data.ts
  models/Activity/Agenda.ts
  models/Activity/index.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/community/[community].tsx
  pages/community/index.tsx
  pages/project/issues/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#174 [add] Lark Image component for Safe Loading
  components/Activity/Agenda/Card.tsx
  components/Activity/Card.tsx
  components/Article/Card.tsx
  components/Community/CommunityCard.tsx
  components/Community/MemberCard.tsx
  components/Department/Card.tsx
  components/Election/ElectorCard.tsx
  components/LarkImage.tsx
  components/Layout/MainNav.tsx
  components/Organization/Card.tsx
  pages/index.tsx
  pages/organization/cooperation.tsx
Labels: enhancement

#179 [optimize] Only display member records whose approver information is not empty
  models/Community/CommunityMember.ts
  models/Community/index.ts
  pages/community/[community].tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: bug

#172 add: QRCode for each agenda and Session box
  .env
  .env.development
  .npmrc
  README.md
  components/Activity/Agenda/Toolbar.tsx
  components/LanguageMenu.tsx
  components/Layout/SessionBox.tsx
  models/Activity/Agenda.ts
  models/Activity/CheckEvent.ts
  models/Base/User.ts
  models/Base/index.ts
  next.config.mjs
  package.json
  pages/_document.tsx
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pnpm-lock.yaml
Labels: feature

#188 [add] activity add alias path
  components/Activity/Card.tsx
  models/Activity/index.ts
Labels: enhancement

#185 [add] homepage activity card
  components/Activity/Card.tsx
  models/Activity/index.ts
  pages/index.tsx
  styles/Home.module.less
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#183 [optimize]: add activity articles calendar
  components/data.ts
  models/Product/Article.ts
  package.json
  pages/activity/[id]/index.tsx
  pages/activity/calendar/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#192 [optimize]: add add previous activity Button
  pages/activity/[id]/index.tsx
  pages/search/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#190 [add] Activity Gift model & page
  components/Activity/Agenda/Card.tsx
  components/Activity/Agenda/Toolbar.tsx
  components/Activity/Card.tsx
  components/Activity/CheckConfirm.tsx
  components/Activity/GiftCard.module.less
  components/Activity/GiftCard.tsx
  components/Article/Card.tsx
  components/Base/CommentBox.tsx
  components/Base/LanguageMenu.tsx
  components/Base/LarkImage.tsx
  components/Base/LazyImage.tsx
  components/Base/PillTab.tsx
  components/Base/QRCodeButton.tsx
  components/Base/SearchBar.module.less
  components/Base/SearchBar.tsx
  components/Community/CommunityCard.tsx
  components/Community/MemberCard.tsx
  components/Department/Card.tsx
  components/Election/ElectorCard.tsx
  components/Issues/Card.tsx
  components/Layout/MDX.tsx
  components/Layout/MainNav.tsx
  components/Member/Card.tsx
  components/Organization/Card.tsx
  models/Activity/CheckEvent.ts
  models/Activity/Gift.ts
  models/Activity/index.ts
  models/Repository.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/gift.tsx
  pages/activity/[id]/index.tsx
  pages/activity/[id]/volunteer.tsx
  pages/activity/calendar/index.tsx
  pages/article/[id]/index.tsx
  pages/index.tsx
  pages/member/[name].tsx
  pages/organization/cooperation.tsx
  pages/project/issues/index.tsx
  pnpm-lock.yaml
Labels: feature

#196 [add] User Menu component
  components/Activity/Agenda/Toolbar.tsx
  components/Activity/CheckConfirm.tsx
  components/Base/UserMenu.tsx
  components/Layout/MainNav.tsx
  models/Activity/CheckEvent.ts
  package.json
  pages/_app.tsx
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/gift.tsx
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
Labels: enhancement
