Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2023-12, with the labels that each got.

#275 Fix ：department query error
  .gitignore
  components/Base/TextScrollableBox/style.module.less
  components/Department/Card.tsx
  components/Department/Tree.tsx
  components/Member/Title.tsx
  pages/api/search.ts
  pages/department/[name].tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#277 [refactor] simplify Member & Department pages based on Member Group component
  components/Department/Card.tsx
  components/Member/Group.tsx
  components/Member/Title.tsx
  docker-compose.yml
  models/Personnel/Department.ts
  package.json
  pages/department/[name].tsx
  pages/member/index.tsx
  pages/search/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#278 [optimize] Long List render performance
  components/Activity/Agenda/Card.tsx
  components/Activity/Card.tsx
  components/Activity/GiftCard.module.less
  components/Activity/GiftCard.tsx
  components/Article/Card.tsx
  components/Community/CommunityCard.tsx
  components/Community/MemberCard.tsx
  components/Election/ElectorCard.tsx
  components/Git/Card.tsx
  components/Issues/IssueModule.tsx
  components/Map/ListMap.tsx
  components/Member/Card.module.less
  components/Organization/Card.tsx
  pages/department/[name].tsx
  styles/globals.less
Labels: bug

#279 [add] Lark notification of Vercel preview URL
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  package.json
  pages/department/[name].tsx
  pnpm-lock.yaml
Labels: enhancement

#280 [add] XiaoYuan Chat Bot based on AI Table
  .github/workflows/main.yml
  .github/workflows/pull-request.yml
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pnpm-lock.yaml
Labels: feature

#251 feat: show location and url on agenda calendar
  components/Activity/Agenda/Card.tsx
  components/Activity/Agenda/Toolbar.tsx
  models/Activity/Agenda.ts
  models/Activity/Forum.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/index.tsx
Labels: enhancement

#284 [add] Sentry monitor configuration
  .env
  README.md
  components/Map/CityStatisticMap.tsx
  components/Map/ListMap.tsx
  components/data.ts
  docker-compose.yml
  models/Activity/index.ts
  models/Product/Article.ts
  next.config.mjs
  package.json
  pages/_document.tsx
  pages/_error.tsx
  pages/api/lark/bitable/v1/[...slug].ts
  pages/community/pioneer.tsx
  pnpm-lock.yaml
  sentry.client.config.ts
  sentry.edge.config.ts
  sentry.server.config.ts
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#285 [add] Time Range component
  Dockerfile
  components/Activity/Agenda/Card.tsx
  components/Base/TimeRange.tsx
  models/Activity/index.ts
  models/Product/Article.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/community/pioneer.tsx
  pages/user/[uuid].tsx
Labels: enhancement

#287 feat: limit container use mem
  docker-compose.yml
Labels: enhancement
