Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2023-07, with the labels that each got.

#120 Feat invitation card
  models/Base.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/invitation.module.less
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
  public/image/bg.png
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#121 [refactor] style & logic of Invitation Generator
  components/Activity/Agenda/Card.tsx
  models/Activity.ts
  models/Agenda.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/invitation.module.less
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
  public/image/bg.png
Labels: enhancement

#122 agenda detail page
  components/Activity/Agenda/Card.tsx
  models/Agenda.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#124 [add] Agenda People component & Normalize Text Array method
  components/Activity/Agenda/People.tsx
  models/Agenda.ts
  models/System.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.module.less
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/api/lark/core.ts
  pnpm-lock.yaml
Labels: enhancement

#125 [add] Agenda Toolbar component with iCalendar support
  components/Activity/Agenda/Card.tsx
  components/Activity/Agenda/Toolbar.tsx
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#126 [feat] add forum model and use activityPeople component for activity page
  components/Activity/Agenda/People.tsx
  components/Group/Card.tsx
  components/Organization/Card.tsx
  models/Activity.ts
  models/Forum.ts
  pages/activity/[id]/index.tsx
  pages/activity/index.tsx
  pages/api/lark/core.ts
  pages/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#127 [feat] add Image Carousel for Activity Agenda Card
  components/Activity/Agenda/Card.tsx
Labels: enhancement

#133 [refactor] rewrite Election card & list page with new Data structure
  .env
  components/Election/ElectorCard.tsx
  models/Cooperation.ts
  models/Elector.ts
  models/Person.ts
  models/Personnel.ts
  models/System.ts
  package.json
  pages/api/search.ts
  pages/election/[year]/elector/[id].tsx
  pages/election/[year]/index.tsx
  pages/person/[name].tsx
  pages/search/index.tsx
  pnpm-lock.yaml
Labels: feature

#139 [optimize] Update navigation content; Add our vision
  components/MainNav.tsx
  components/data.ts
  pages/_document.tsx
  pages/api/home.ts
  pages/article/index.tsx
  pages/department/index.tsx
  pages/index.tsx
  pages/person/[name].tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#140 [feat] add default avatar for people component
  components/Activity/People.tsx
Labels: bug

#141 [refact] nav component
  components/Activity/DrawerNav.tsx
  package.json
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
Labels: enhancement
