Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2023-01, with the labels that each got.

#95 [style] Adjust the article listing style
  components/Activity/Card.tsx
  components/Article/Card.tsx
  pages/_document.tsx
  styles/globals.less
Labels: bug

#94 [add] Agenda model & Activity Detail page
  .env.development
  .env.production
  components/Activity/Agenda/Card.tsx
  components/Activity/Card.tsx
  components/Activity/List.tsx
  components/Article/List.tsx
  components/MainNav.tsx
  models/Activity.ts
  models/Agenda.ts
  models/Organization.ts
  package.json
  pages/activity/[id]/index.tsx
  pages/activity/index.tsx
  pages/api/activity/index.ts
  pages/api/article/index.ts
  pages/api/base.ts
  pages/api/lark/bitable/v1/[...slug].ts
  pages/api/lark/core.ts
  pages/article/[id]/index.tsx
  pages/article/index.tsx
  pages/index.tsx
  pages/members/index.tsx
  pages/organization/cooperation.tsx
  pages/search/index.tsx
  pnpm-lock.yaml
Labels: enhancement, feature

#99 [refactor] simplify Lark API wrappers based on MobX-Lark
  components/Group/Card.tsx
  models/Activity.ts
  models/Agenda.ts
  models/Article.ts
  models/Base.ts
  models/Cooperation.ts
  models/Elector.ts
  models/Group.ts
  models/Lark.ts
  models/Member.ts
  models/Organization.ts
  models/System.ts
  package.json
  pages/activity/[id]/index.tsx
  pages/api/lark/bitable/v1/[...slug].ts
  pages/api/lark/core.ts
  pages/api/lark/file/[id].ts
  pages/api/search.ts
  pages/article/[id]/index.tsx
  pages/election/[year]/index.tsx
  pages/organization/cooperation.tsx
  pnpm-lock.yaml
Labels: feature

#100 [optimize] rewrite Fallback paths to GitHub pages
  models/Activity.ts
  next.config.js
  package.json
  pnpm-lock.yaml
Labels: bug
