Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2023-08, with the labels that each got.

#136 [refactor] Member pages & Department tree based on Personnel & Department models
  .env
  components/Election/ElectorCard.tsx
  components/Group/Card.tsx
  components/Group/Tree.tsx
  components/Member/Card.tsx
  components/Member/List.module.less
  components/Member/List.tsx
  components/Member/Static.tsx
  components/Member/Tabs.tsx
  components/Member/Title.tsx
  components/data.ts
  models/Activity.ts
  models/Agenda.ts
  models/Expert.ts
  models/Forum.ts
  models/Group.ts
  models/Member.ts
  models/Organization.ts
  models/Person.ts
  models/Personnel.ts
  package.json
  pages/api/search.ts
  pages/department/committee/[name].tsx
  pages/department/council.tsx
  pages/department/index.tsx
  pages/election/[year]/index.tsx
  pages/index.tsx
  pages/member/[name].tsx
  pages/member/index.tsx
  pages/members/expert.tsx
  pages/members/index.tsx
  pages/search/index.tsx
  pages/tool/license-filter.tsx
  pnpm-lock.yaml
Labels: feature

#143 [migrate] replace Built-in middlewares with Next SSR middleware
  components/Member/Card.tsx
  models/Activity.ts
  models/Agenda.ts
  models/Forum.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/index.tsx
  pages/activity/index.tsx
  pages/api/base.ts
  pages/article/[id]/index.tsx
  pages/article/index.tsx
  pages/department/committee/[name].tsx
  pages/department/council.tsx
  pages/department/index.tsx
  pages/election/[year]/index.tsx
  pages/index.tsx
  pages/member/[name].tsx
  pages/member/index.tsx
  pages/organization/cooperation.tsx
  pages/organization/index.tsx
  pages/organization/landscape.tsx
  pages/search/index.tsx
  pnpm-lock.yaml
Labels: feature

#146 [add] Activity Map component & Place model
  components/Activity/Card.tsx
  components/Activity/Map.tsx
  models/Activity.ts
  models/Forum.ts
  models/Place.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
Labels: feature

#148 Update README.md
  README.md
Labels: bug

#149 [refactor] replace Activity Map with List Map component
  components/Activity/Map.tsx
  components/ListMap.tsx
  models/Personnel.ts
  models/Place.ts
  models/System.ts
  package.json
  pages/_document.tsx
  pages/activity/[id]/index.tsx
  pages/api/lark/core.ts
  pnpm-lock.yaml
Labels: enhancement

#152 [optimize] Article List page supports Type filter
  components/data.ts
  package.json
  packages.d.ts
  pages/activity/[id]/index.tsx
  pages/article/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#155 [optimize] simplify China Map component based on Open React Map
  README.md
  components/Activity/DrawerNav.tsx
  components/Activity/People.tsx
  components/ChinaMap.tsx
  components/CityStatisticMap.tsx
  components/ListMap.tsx
  components/Organization/Card.tsx
  components/Organization/index.tsx
  models/Activity.ts
  models/Agenda.ts
  models/Bill.ts
  models/Cooperation.ts
  models/Organization.ts
  models/Personnel.ts
  models/System.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/finance.tsx
  pages/activity/[id]/index.tsx
  pages/organization/index.tsx
  pnpm-lock.yaml
Labels: enhancement
