Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2023-10, with the labels that each got.

#198 [add] User Profile page
  components/Activity/Agenda/Toolbar.tsx
  components/Activity/CheckConfirm.tsx
  components/Base/UserMenu.tsx
  models/Activity/CheckEvent.ts
  models/Base/User.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/user/[uuid].tsx
  pnpm-lock.yaml
Labels: feature

#199 [add] Agenda Evaluation model, form & score
  components/Activity/Agenda/Card.tsx
  components/Base/ScoreBar.tsx
  models/Activity/Agenda.ts
  models/Activity/CheckEvent.ts
  models/Activity/Evaluation.ts
  models/Activity/index.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/gift.tsx
  pages/activity/[id]/index.tsx
  pages/user/[uuid].tsx
  pnpm-lock.yaml
Labels: feature

#204 add: add recommend agenda list
  components/Activity/Agenda/FileList.tsx
  components/data.ts
  models/Activity/Agenda.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#213 [add] Sub Page navigators & Agenda Mentor organization
  README.md
  components/Activity/Agenda/Card.tsx
  models/Activity/Agenda.ts
  models/Base/User.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/finance.tsx
  pages/activity/[id]/gift.tsx
  pages/activity/[id]/volunteer.tsx
  pages/activity/calendar/index.tsx
  pages/article/[id]/index.tsx
  pages/community/[community].tsx
  pages/department/committee/[name].tsx
  pages/department/council.tsx
  pages/member/[name].tsx
  pages/organization/landscape.tsx
  pages/project/issues/index.tsx
  pages/user/[uuid].tsx
  pnpm-lock.yaml
  styles/globals.less
Labels: enhancement

#209 optimize: activity detail layout ; agenda detail recommends data search by tags
  components/Activity/Agenda/Card.tsx
  models/Activity/Agenda.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/index.tsx
Labels: enhancement

#216 [optimize] reduce Call Count of GitHub API
  README.md
  models/Repository.ts
  pages/project/index.tsx
  pages/project/issues/index.tsx
Labels: enhancement

#218 fix: add mail for Deparment; add `特别支持`; set `白金赞助` as Single Line Benefits Levels
  components/Department/Card.tsx
  pages/organization/cooperation.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: bug

#219 fix：update agenda card layout
  components/Activity/Agenda/Card.tsx
  components/Activity/Agenda/Toolbar.tsx
  components/Activity/index.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/index.tsx
Labels: bug

#224 [fix] avatars undefined error
  components/Activity/Agenda/Card.tsx
Labels: bug

#205 Fix GitHub api limit
  models/Base/index.ts
  pages/api/github/[...slug].ts
  pages/api/github/core.ts
Labels: enhancement

#221 update: license filter
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: bug

#226 feat: docker container autostart
  docker-compose.yml
Labels: feature

#229 [fix] Image lazy loading
  components/Activity/People.tsx
  components/Base/LarkImage.tsx
  components/Base/LazyImage.tsx
  components/Map/ListMap.tsx
  components/Member/Card.tsx
  package.json
  pnpm-lock.yaml
Labels: bug

#232 feat: enhance profile display of producers and mentors
  components/Activity/People.tsx
  models/Activity/Forum.ts
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/index.tsx
  pnpm-lock.yaml
Labels: enhancement

#233 feat: google analytics
  pages/_app.tsx
Labels: enhancement

#238 feat: limit docker log size
  docker-compose.yml
Labels: enhancement

#244 [chore] docker compose configuration
  docker-compose.yml
Labels: bug

#241 [optimize] enable Auto Check Event
  .env
  components/Activity/CheckConfirm.tsx
  models/Activity/Agenda.ts
  models/Base/System.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/activity/[id]/agenda/[agendaId]/index.tsx
Labels: enhancement

#246 [add] Original Link of Article Detail page
  components/Activity/Agenda/Card.tsx
  components/Base/LarkImage.tsx
  components/Organization/Card.tsx
  models/Activity/Forum.ts
  models/Product/Article.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/index.tsx
  pages/article/[id]/index.tsx
  pages/member/[name].tsx
  pnpm-lock.yaml
Labels: enhancement

#249 fix: nav bar dropdown list title display
  components/Layout/MainNav.tsx
Labels: bug

#235 optimal license filter
  pages/tool/license-filter.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#261 [optimize] upgrade to React 18 & Next.js 14
  components/Activity/Agenda/Card.tsx
  components/Activity/Agenda/Toolbar.tsx
  components/Activity/Card.tsx
  components/Activity/GiftCard.tsx
  components/Activity/index.ts
  components/Article/Card.tsx
  components/Base/TagNav.tsx
  components/Community/CommunityCard.tsx
  components/Community/MemberCard.tsx
  components/Department/Card.tsx
  components/Election/ElectorCard.tsx
  components/Layout/MainNav.tsx
  components/Layout/PageHead.tsx
  components/Organization/Card.tsx
  components/Organization/index.tsx
  models/Base/System.ts
  package.json
  pages/_app.tsx
  pages/activity/[id]/agenda/[agendaId]/index.tsx
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/activity/[id]/finance.tsx
  pages/activity/[id]/gift.tsx
  pages/activity/[id]/index.tsx
  pages/activity/[id]/volunteer.tsx
  pages/activity/calendar/index.tsx
  pages/article/[id]/index.tsx
  pages/index.tsx
  pages/member/[name].tsx
  pnpm-lock.yaml
Labels: enhancement
