Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2024-01, with the labels that each got.

#289 feat: use libjemalloc
  Dockerfile
Labels: enhancement

#292 [add]honor page (#144)
  components/data.ts
  pages/community/honor/[name].tsx
  pages/community/pioneer.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#291 [optimize] move Authing Guard instance to SSR component
  .env
  Dockerfile
  components/Base/UserMenu.tsx
  components/Layout/SessionBox.tsx
  components/data.ts
  models/Base/User.ts
  next.config.mjs
  package.json
  pages/_error.tsx
  pages/api/search.ts
  pages/community/award/[name].tsx
  pages/community/honor/[name].tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#294 feat: GC config
  Dockerfile
Labels: bug

#295 [optimize] add meeting calendar page
  components/data.ts
  pages/meeting-calendar/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#298 [add] Election index page
  .husky/pre-commit
  .husky/pre-push
  components/Election/ElectorCard.tsx
  components/data.ts
  models/Personnel/index.ts
  package.json
  pages/election/[year]/index.tsx
  pages/election/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#297 [fix]Fixed internal honor data duplication issue
  pages/community/award/[name].tsx
Labels: bug

#300 [refactor] add independent Share Box component
  Dockerfile
  components/Base/ShareBox.tsx
  models/Base/System.ts
  models/Personnel/index.ts
  package.json
  pages/activity/[id]/agenda/[agendaId]/invitation.tsx
  pages/election/[year]/index.tsx
  pages/election/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#301 [add] Candidate Poster page of Election system
  components/Election/ElectorCard.tsx
  models/Personnel/index.ts
  pages/election/[year]/candidate/[recipient]/poster/[position].tsx
  pages/election/[year]/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature
