Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2024-07, with the labels that each got.

#315 [add]Activity Statistics Page
  components/Activity/Charts.tsx
  models/Activity/Agenda.ts
  pages/activity/[id]/charts/index.tsx
  pages/activity/[id]/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#316 build: change scp github action
  .github/workflows/deploy-production.yml
Labels: bug

#317 build: update docker github action
  .github/workflows/deploy-production.yml
Labels: enhancement
