Repository kaiyuanshe/kaiyuanshe.github.io, pull requests merged in 2024-11, with the labels that each got.

#347 成员看板
  pages/member/[name].tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement

#365 [fix] set Gray Scale only for Current Year
  package.json
  pages/activity/[id]/gift.tsx
  pages/activity/[id]/index.tsx
  pages/api/base.ts
  pages/department/[name]/[year].tsx
  pages/index.tsx
  pages/member/[name].tsx
  pnpm-lock.yaml
Labels: bug

#368 意见箱 功能
  .env
  components/Issue/Card.tsx
  components/Issue/List.tsx
  components/data.ts
  models/Governance/Issue.ts
  package.json
  pages/governance/issue/index.tsx
  pnpm-lock.yaml
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#370 提案库
  .env
  components/Proposal/Card.tsx
  components/Proposal/List.tsx
  components/data.ts
  models/Governance/Proposal.ts
  pages/governance/issue/index.tsx
  pages/governance/proposal/index.tsx
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: feature

#371 意见箱 提案库显示更多信息
  components/Issue/Card.tsx
  components/Proposal/Card.tsx
  models/Governance/Issue.ts
  models/Governance/Proposal.ts
  translation/en-US.ts
  translation/zh-CN.ts
  translation/zh-TW.ts
Labels: enhancement
